### ISSUE TITLE
GET API for AirTable (mentors)

### ISSUE THREAD

**Issue by MishFTW** [optimizemi/optiPortal#8]
Build functionality for getting mentor data from AirTable's mentors directory.

**Comment by FuzedxPheonix** [comment]
Currently created a branch called cristian-dev which would be doing this.

**Comment by MishFTW** [comment]
> Currently created a branch called cristian-dev which would be doing this.

Please branch per issue, and only work on that issue in the branch. Following standard Git flow! Thanks :)

**Comment by FuzedxPheonix** [comment]
Still setting up the server and just got access to Airtable hopefully before the meeting I should have everything working!
